-- Create Mariners table
CREATE TABLE mariners (
    mariner_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    address VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(20),
    date_joined DATE,
    status ENUM('Active', 'Inactive'),
    password VARCHAR (255) NOT NULL
);


-- Insert data into Mariners table
INSERT INTO mariners (first_name, last_name, address, email, phone_number, date_joined, status, password)
VALUES
    ('Aurora', 'Frost', '12 Main Street, Queenstown, NZ', 'aurora.frost@gmail.com', '021 123 4567', '2023-01-15', 'Active', 'bb3a42c5402cefcbe914440d61d2e4ed66f1e227cea94bc735522cdad368c6bb'),
    ('Benjamin', 'Hayes', '4 Beach Road, Auckland, NZ', 'benjamin.hayes@gmail.com', '021 111 2355', '2022-02-08', 'Active', '23d034676ecd750104a0f145ee33b77014ab1710f9cbd8ed5c06901ef3d29056'),
    ('Isabella', 'Rivera', '7 Oak Street, Auckland, NZ', 'isabella.rivera@gmail.com', '027 345 4489', '2023-11-03', 'Active', '82a722e43f67d27c431bf0aea2317284f917536cd0fddeb831c73bb63ca95d23'),
    ('Ethan', 'Clarke', '101 Pine Lane, Hamilton, NZ', 'ethan.clarke@hotmail.com', '021 343 2223', '2021-03-20', 'Active', 'c32649b794b7ba2e086763a463821d24dd77e521a724bca5d54c97e00d2a2a60'),
    ('Sophia', 'Nguyen', '20 Cedar Road, Christchurch, NZ', 'sophia.nguyen@hotmail.com', '027 564 8901', '2023-07-11', 'Active', '95378d490ec1cb9c50c60113db288e6954c03eb9e1dd5ee2790fbdbd1d8527ae');





-- Create staff table

CREATE TABLE staff (
    staff_number INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    work_phone VARCHAR(20),
    hire_date DATE,
    position VARCHAR(20),
    department VARCHAR(50),
    status ENUM('Active', 'Inactive'),
    password VARCHAR(255) NOT NULL
);


-- Insert data into staff table
INSERT INTO staff (first_name, last_name, email, work_phone, hire_date, position, department, status, password) VALUES
('John', 'Smith', 'john.smith@gmail.com', '021 033 4567', '2022-05-15', 'Staff', 'Field Operations', 'Active', '7731a6bb815c14b53bca6762e3929b19f1ee566ab7531d4198607b426833cd62'),
('Emily', 'Johnson', 'emily.johnson@hotmail.com', '022 987 5543', '2018-09-08', 'Staff', 'Compliance', 'Active', '185880ce1f2c0ea48ff7a5e0313ad83d0cb99f469f4dd5a900aae64d94c6aeb7'),
('Michael', 'Brown', 'michael.brown@outlook.com', '027 226 3333', '2020-01-20', 'Staff', 'Research & Development', 'Inactive', 'db8077b969926b4a2066fe9f31152f7a225682a6a6aa907299fdadc452ac4429');



-- Create admin table

CREATE TABLE admin (
    staff_number INT NOT NULL PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    work_phone VARCHAR(20),
    hire_date DATE,
    position VARCHAR(20),
    department VARCHAR(50),
    status ENUM('Active', 'Inactive'),
    password VARCHAR(255) NOT NULL
);

-- Insert data into admin table

INSERT INTO admin (staff_number, first_name, last_name, email, work_phone, hire_date, position, department, status, password) VALUES
('0', 'Sarah', 'Martinez', 'sarah.martinez@gmail.com', '021 444-5555', '2008-11-08', 'Admin', 'Administration', 'Active', '24737c9d365948e5ccd749817a9f3ced7313d5478c905535d4092cb0035d0c2f');



    

-- Create OceanPestsDiseases table

CREATE TABLE oceanpestsdiseases (
    oceanID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OceanItemType ENUM('Pest', 'Disease'),
    PresentInNZ ENUM('Yes', 'No'),
    CommonName VARCHAR(100),
    ScientificName VARCHAR(100),
    KeyCharacteristics TEXT,
    BiologyDescription TEXT,
    Threats TEXT,
    Location TEXT,
	PrimaryImage VARCHAR(100),
	SecondaryImage VARCHAR(100)
);




-- Insert data into table

INSERT INTO oceanpestsdiseases (OceanItemType, PresentInNZ, CommonName, ScientificName, KeyCharacteristics, BiologyDescription, Threats, Location, PrimaryImage, SecondaryImage) VALUES
('Pest', 'Yes', 'Asian Paddle Crab', 'Charybdis japonica', 'Six spikes on each side of shell; Five spines on upper surface of front claw; Flattened swimming paddles on back legs; Adult shell width up to 12 cm; Shell color ranges from off-white and pale green, through olive green to a deep chestnut brown with purplish markings', 'Aggressive crab that can out-compete native crabs for space and food.', 'Threat to aquaculture as it preys on shellfish; Can carry White Spot Syndrome virus which can infect native and farmed prawns, crabs, and lobsters', 'Firm sand or muddy fine sand bottoms; Estuarine and marine areas; 0 – 15 meters depth', 'Asian Paddle Crab1.png', 'Asian Paddle Crab2.png'),
('Pest', 'Yes', 'Pyura', 'Pyura praeputialis', 'Hard sack-like body with brown or reddish-brown leathery skin; Sand and shell material or algae may be incorporated into outer skin; Flat upper surface surrounded by a ridge, and two siphons close together that project slightly above the flat surface; Adults 15 cm or more in height (max 30 cm) and approx 3–5 cm diameter; Underwater, a distinctive “cross” may be visible in siphon openings', 'Forms dense populations or mats that could displace important native species including green shell mussels.', 'Forms dense populations or mats, and can survive in a wide geographical range; Could displace important native New Zealand species, including green shell mussels', 'Rocky intertidal, or rocky surfaces in the shallows; Forms a mat over rocks that is often clearly visible at low tide', 'Pyura1.jpg', 'Pyura2.png'),
('Pest', 'Yes', 'Australian Droplet Tunicate', 'Eudistoma elongatum', 'White or cream-colored cylindrical tubes or “tunics”; Generally 5–20 mm in diameter; Tubes generally 5–30 cm long – but can reach 1.5 meters; The white tunics contain many small individual organisms and can sometimes appear orange-flecked due to the bright orange larvae within them', 'Unsightly fouling of coastal environments and coastal marine infrastructure. Fouling nuisance for marine farming.', 'Unsightly fouling of coastal environments and coastal marine infrastructure; Fouling nuisance for marine farming', 'Sheltered bays and harbors; Attached to any hard surfaces present, including rocky outcrops, cobbles, pebbles, shell pieces, and artificial structures e.g., wharf piles and oyster racks. Often found attached to pieces of shell and twigs buried just below the surface of the sediment. Also often found unattached lying in depressions in the sediment and amongst eelgrass beds; Low intertidal to subtidal; Generally submerged just below the waterline, but can often be seen at low tide', 'Australian Droplet Tunicate1.png', 'Australian Droplet Tunicate2.png'),
('Pest', 'No', 'Northern Pacific Seastar', 'Asterias amurensis', 'Five arms with pointed, upturned tips; Yellow/orange, often with purple markings on top – yellow underneath; Arms covered with numerous unevenly-arranged small spines; Generally 12 cm to 24 cm across, but can grow to 40–50 cm', 'Voracious predator of native species and economically important farmed shellfish.', 'Voracious predator of native species and economically important farmed shellfish; Potentially serious impacts on aquaculture, fisheries, and wild shellfish populations', 'Grows best in cold temperate.; Down to 200 meters depth – usually shallower than 25 meters.; Mud, sand, or pebbles, or artificial structures including wharf piles and mussel lines; Prefers sheltered waters – estuaries, bays, rock pools', 'Northern Pacific Seastar1.png', 'Northern Pacific Seastar2.png'),
('Pest', 'Yes', 'Japanese Kelp', 'Undaria pinnatifida', 'Brown to yellow-green coloured kelp, 1–3 meters in length; Frilly sporophyll near the base of mature plants; Strap-like midrib in mature plants; Smooth thin blades or leaves that stop well short of the base', 'Rapidly forms dense stands that overgrow and exclude native seaweed species.', 'Rapidly forms dense stands that overgrow and exclude native seaweed species; Nuisance fouling can cause problems and increased costs for aquaculture', 'Grows best in cold temperate ocean waters; Low intertidal to approximately 20 meters depth; Highest density occurs between 1 and 3 meters depth; Grows on any hard surface including rocky shores and reefs and artificial structures such as wharves, vessel hulls, and aquaculture equipment; Tolerates a wide range of wave exposures, from sheltered marinas to open coast', 'Japanese Kelp1.png', 'Japanese Kelp2.png'),
('Pest', 'No', 'European Shore Crab', 'Carcinus maenas', 'Adult shell width up to 8 cm; Five spines or spikes on each side of shell; Adult color varies from green top and yellowish underside, to red/orange mottled above and orange or partly red underneath; Juveniles generally lighter in color than adults; Three rounded teeth or lobes between the eyes; No swimming paddles on legs', 'Voracious predator – eats mussels, crabs, oysters, limpets, barnacles, and worms. Also juvenile crabs and shellfish, including scallops.', 'Highly adaptable invasive species; Voracious predator – eats mussels, crabs, oysters, limpets, barnacles, and worms. Also juvenile crabs and shellfish, including scallops; Potential to significantly alter ecosystems causing mortality in native crab and shellfish populations; Has been implicated in the decline of native shellfish populations overseas, some of commercial importance', 'All types of protected and semi-protected marine and estuarine habitats, including mud, sand, rocky substrates, and seagrass beds; From the intertidal to 60 meters deep Predominantly a shore to shallow water species', 'European Shore Crab1.png', 'European Shore Crab2.png'),
('Pest', 'No', 'Chinese Mitten Crab', 'Eriocheir sinensis', 'Hairy “mittens” on front claws – unlike any New Zealand crab; Mitten claws have white pincer tips; Four spines or serrations on each side of the shell; Distinct notch between eyes; Light-brown to olive green shell – up to 10 cm across', 'Burrowing weakens banks of estuaries, accelerating erosion. Can carry a liver fluke which can harm human health.', 'Burrowing weakens banks and causes accelerated erosion; Damage to fishing nets and catch; High densities can block water intakes in irrigation and hydroelectric schemes; Can carry a liver fluke which can harm human health', 'Brackish to fresh waters of estuaries, rivers, and streams; Substrate varies from mud to sand and rocky; Burrows can be up to 1.2 meters deep and 2 meters long; Typically occur from intertidal to 20 meters depth', 'Chinese Mitten Crab1.png', 'Chinese Mitten Crab2.png'),
('Pest', 'No', 'Asian Clam', 'Potamocorbula amurensis', 'Has a distinctive overbite – the two shells are uneven in size; Shell dirty white, tan, or yellow in color – frequently with brown staining; Thin and smooth shell (older shells may be wrinkled at edges); Generally 2–3 cm in length. But can be as small as 0.5 cm', 'Forms huge populations, competing with native species for food.', 'Reduces planktonic food sources, causing a decline in abundance and diversity of native species, and decline or collapse of commercial fisheries and farmed shellfish; Reaches extremely high population densities, altering the soft sediment community structure of an area by changing the sediment structure and reducing the space available for other species', 'Most often on mixed sand and mud substrates; Clams are partially buried in soft material with ½ to of shell exposed above the surface; Mostly subtidal, but also intertidal; Can live in almost freshwater upper estuarine creek areas through to fully marine habitats; Subtropical to cold temperate waters', 'Asian Clam1.png', 'Asian Clam2.png'),
('Pest', 'No', 'Aquarium Caulerpa', 'Caulerpa taxifolia', 'Bright green seaweed; Horizontal runners reach up to nine meters; Runners give rise to many upright fronds; Fronds are flattened with a smooth and distinct midrib; Fronds up to 1 cm wide and up to 15 cm long (up to 60 cm in deep water); Pinnules (or individual leaves) attach to mid-rib directly opposite one another', 'Aggressive weed that can quickly spread and smother native species.', 'Aggressive weed that can quickly spread and smother other algae, seagrasses, and invertebrate communities; Out-competes native species for food or light and produces toxic compounds; Vast beds can destroy native species diversity and fish habitat; Tangles in nets and anchors; If aquarium Caulerpa escaped into the marine environment there is a high risk of it establishing and severely damaging the marine environment', 'Up to 100 meters depth, but usually between 3–35 meters; Rock, sand, mud, and seagrass beds; Exposed and sheltered estuaries, coastal lagoons, and bays; Tolerates a wide range of water temperatures; A common aquarium weed overseas – infestations can occur in the wild where aquariums are emptied into the sea, drains, or other waterways; It is an offense to import, grow, or spread this weed. The aquarium trade is still the most likely route of entry for Caulerpa into New Zealand', 'Aquarium Caulerpa1.png', 'Aquarium Caulerpa2.png'),
('Pest', 'Yes', 'Mediterranean Fanworm', 'Sabella spallanzanii', 'Spiral fan of feeding tentacles on top of leathery tube; Fan is white banded with pale fawn/orange or brown; Tube is tough and flexible, dull grey-brown colored and up to 40 cm; Tube is often muddy in appearance with other organisms growing on it; Commonly forms clumps of several individuals, creating a canopy of feeding fans', 'Forms dense groups competing with native species for food and space.', 'Can form dense groups; Competes with native species for food and space; Can have a negative impact on the establishment of new generations of some species, and on nutrient flow; Dense beds can foul fishing equipment or aquaculture structures', 'Attaches to hard surfaces including rocks, concrete, and seabed organisms such as mussels and oysters; Has been found on boat hulls and wharf and marina structures; Sheltered temperate waters, up to 30 meters depth', 'Mediterranean Fanworm1.png', 'Mediterranean Fanworm2.png'),
('Pest', 'Yes', 'Clubbed Tunicate/Leathery Sea Squirt', 'Styela clava', 'Tubular, club-shaped body that tapers to a stalk; Leathery, bumpy, often wrinkled outer skin; Brown-colored; Two short siphons or holes on end; Up to 16 cm long; Often thickly covered with other marine fouling growth; Grows as single individuals', 'Fast-growing nuisance fouler of vessels, marine farms, and fishing equipment. Competes with native species for food and space.', 'Fast-growing and can form dense groups; A filter feeder that can compete with native and aquaculture species for food (planktonic larvae) and space; Nuisance fouler of vessels, aquaculture, and fishing equipment and other artificial structures', 'Attaches to hard surfaces in sheltered areas away from wave action; Found on rocks, oyster and mussel shells, and seaweed; Commonly attaches to man-made structures such as boat hulls, wharves, and mussel lines; Low intertidal zone (area between high and low tides) to 25 meters depth', 'Clubbed Tunicate1.jpg', 'Clubbed Tunicate2.png'),
('Pest', 'No', 'Asian Brown Mussel', 'Perna perna', 'Generally a brown or brown-yellow color and can be tinged with green around the edges; Grow to a length of about 90 mm but can reach up to 120 mm; Main difference between this mussel species and others is the angle of the shell', 'If established in New Zealand, it could make life hard for our native green-lipped mussels. A close relative of the native green-lipped mussel, it lives in similar places and eats the same food.', 'Competes for food and space with green-lipped mussels; Thrives on human structures and can create fouling problems in places like jetties, buoys, and boat hulls; Could bring new diseases to New Zealand that could harm native shellfish', 'More likely to be found in the north of New Zealand due to warm temperatures needed for reproduction, but can survive nearly anywhere in New Zealand waters', 'Asian Brown Mussel1.jpg', 'Asian Brown Mussel2.jpg'),
('Disease', 'No', 'Withering Abalone Syndrome', 'Xenohaliotis californiensis', 'Attacks the digestive system of abalone, causing them to become weak and shriveled; Main sign of infection is a withered "foot", the part of a pāua that attaches to rocks, while shells remain intact but the body is shrunken inside', 'This disease originates from the west coast of North America and affects the digestive system of abalone, stopping them from eating and causing them to become weak and shriveled.', 'Could harm New Zealand''s pāua species by stunting their growth and making them unappetizing', 'Could hitchhike to New Zealand on used diving gear or aquaculture equipment; Biosecurity New Zealand has strict measures in place to limit the chances of withering abalone syndrome making it through the border, but individuals returning to New Zealand with diving gear should ensure it is dry to minimize the risk of transmission', 'Withering Abalone Syndrome1.jpg', 'Withering Abalone Syndrome2.jpg'),
('Disease', 'No', 'Bacterial Kidney Disease', 'Renibacterium salmoninarum', 'Mostly infects salmon and trout but other species are also at risk; Caused by a bacterium passed from fish to fish and from parent to egg', 'This kidney disease mostly infects salmon and trout but other species are also at risk. It is caused by a bacterium passed from fish to fish and from parent to egg. Prevalent in the Northern Hemisphere and Chile, it was first described in Scotland.', 'Mainly affects Chinook salmon, the main species farmed in New Zealand; Kills large numbers of young fish in both freshwater and seawater; Infected fish can pass the bacteria to their offspring if they survive the infection', 'Infected fish are mostly likely to be found in fish farms, both freshwater and marine', 'Bacterial Kidney Disease1.jpg', 'Bacterial Kidney Disease2.jpg'),
('Pest', 'Yes', 'Asian Date Mussel', 'Arcuatula senhousia (Benson, 1842)', 'Relatively small size and inflated shape; Greenish color of its outer periostracal layer of its shell; Shell has zig-zag markings and iridescent radiating bands; Shell is olive green/brown in color and easily crushed; Can grow as big as 3 cm in length', 'Native to the Pacific Ocean from Siberia to Singapore, the Asian date mussel has spread to numerous locations around the globe incidentally by vessels (as biofouling or larvae in ballast water) and shellfish aquaculture.', 'Alters benthic habitats through forming dense mats on soft sediments that can displace benthic communities; Limits the amount of plankton available as food for other species due to its suspension feeding; Can cause anoxic conditions in the sediment-water interface due to the production and decomposition of large volumes of faeces and pseudofaeces', 'Prefers soft sediments but also fouls artificial hard surfaces, up to 20m depth', 'Asian Date Mussel1.jpg', 'Asian Date Mussel2.jpg'),
('Pest', 'Yes', 'Wakame Asian Kelp', 'Undaria pinnatifida (Harvey) Suringar, 1873', 'Mature plants are brown, green, or yellow in color and grow up to one to two meters; Very visible midrib up the plant; Holdfast anchors them to any hard surface including shells, reefs, ropes, wharf piles, vessel hulls, moorings, and other artificial structures; Sporophyll (a spiral-shaped reproductive structure which produces spores) found at the base of the stem', 'Native to Japan and spread mainly by fouling on vessel hulls, Wakame Asian Kelp is present in almost all of New Zealand''s international ports and harbors, ranging from Auckland down to Bluff, including many offshore islands. It grows from the low intertidal area to subtidal depths of around 15 meters and can form dense "forests" in sheltered reef areas.', 'Can form dense stands underwater, potentially resulting in competition for light and space, leading to the exclusion or displacement of native plant and animal species; Has the potential to become a nuisance for marine farms by increasing labor and harvesting costs due to fouling problems', 'Intertidal to 40 m depth, including wharves, pontoons, buoys, rocky coasts and reefs, boat hulls; grows well in polluted or nutrient-enriched waters', 'Wakame Asian Kelp1.jpg', 'Wakame Asian Kelp2.jpg'),
('Pest', 'Yes', 'Colonial Sea Squirt', 'Didemnum Vexillum', 'Colonial sea squirts form gelatinous colonies composed of individual zooids, which are small filter-feeding organisms. These colonies can vary in color from white to orange or brown and have a soft, mucous-like texture. Individual zooids are interconnected within the colony and share a common tunic.', 'Colonial sea squirts reproduce both sexually and asexually, with larvae settling on surfaces and developing into new colonies. They are filter feeders, drawing in water through siphons and extracting plankton and organic particles for nutrition. Colonies can rapidly expand and cover large areas of substrate, including rocks, pier pilings, and aquaculture infrastructure.', 'Didemnum vexillum poses a threat to native marine biodiversity by outcompeting native species for space and resources. Its rapid growth and ability to form dense colonies can smother native organisms and alter marine habitats.', 'Found in various marine environments, including harbors, estuaries, and coastal waters. Can attach to natural substrates such as rocks and shellfish beds, as well as artificial structures like docks, boat hulls, and aquaculture gear.', 'Colonial Sea Squirt1.jpg', 'Colonial Sea Squirt2.jpg'),
('Pest', 'Yes', 'Japanese Wireweed', 'Sargassum muticum', 'Sargassum muticum is a brown seaweed with a complex branching structure and distinctive air bladders, giving it a buoyant appearance. It can grow to lengths of several meters and forms dense mats on the seabed or floating on the surface. The seaweed''s blades are serrated and often have small, round reproductive structures.', 'Japanese wireweed reproduces via both sexual and asexual means, with dispersal of buoyant reproductive structures facilitating long-distance spread. It is a fast-growing species, capable of colonizing a wide range of substrates, including rocks, docks, and other seaweeds. Sargassum muticum can alter local ecosystems by shading out native species and creating habitat for invasive organisms.', 'This invasive seaweed competes with native marine flora for space and resources, potentially leading to reduced biodiversity. Its ability to form dense mats can smother native seaweeds and disrupt coastal ecosystems. Japanese wireweed may interfere with commercial fishing activities by fouling nets and other gear.', 'Found along coastlines in temperate regions, particularly in sheltered bays, estuaries, and rocky intertidal zones. Commonly observed on rocky substrates and artificial structures such as piers, jetties, and aquaculture facilities.', 'Japanese Wireweed1.jpg', 'Japanese Wireweed2.jpg'),
('Disease', 'Yes', 'Microcell Disease', 'Bonamia ostreae', 'Bonamia ostreae is a microscopic parasite that infects Pacific oysters (Crassostrea gigas). It causes disease in oysters, leading to mortality and reduced growth rates. The parasite can be transmitted through waterborne spores or contaminated equipment.', 'Originally from Europe, Bonamia ostreae has been introduced to New Zealand and other regions. It infects oyster populations, particularly Pacific oysters, impacting aquaculture operations. The parasite can persist in oyster beds, causing ongoing challenges for the industry.', 'Significant economic impacts on the aquaculture industry due to reduced oyster production and mortality. Potential ecological impacts on native shellfish species and associated ecosystems. Management efforts required to control the spread of the parasite and mitigate its impacts.', 'Found in oyster-growing areas along coastlines, particularly where Pacific oysters are cultivated. Commonly observed in aquaculture facilities, natural oyster beds, and areas with high oyster density.', 'Microcell Disease1.jpg', 'Microcell Disease2.jpg'),
('Pest', 'Yes', 'Mediterranean Mussel', 'Mytilus galloprovincialis', 'The Mediterranean mussel has a smooth, elongated shell with a blue-black coloration and concentric growth lines. It typically grows up to 10 centimeters in length and has a triangular shape. This invasive mussel species attaches itself to hard surfaces using byssal threads and forms dense aggregations in coastal habitats.', 'Mytilus galloprovincialis is native to the Mediterranean Sea but has been introduced to various regions worldwide, including New Zealand. It reproduces prolifically, with larvae dispersing through the water column and settling on suitable substrates. The Mediterranean mussel is a filter feeder, consuming plankton and detritus from the surrounding water.', 'This invasive mussel species competes with native bivalves for space and resources, potentially displacing indigenous species. It can form dense mats that smother native flora and fauna, altering ecosystem dynamics and reducing biodiversity. Mediterranean mussels may also foul aquaculture equipment and infrastructure, leading to economic losses.', 'Found in intertidal and subtidal zones along rocky shores, wharves, docks, and other artificial structures. Commonly observed in sheltered coastal areas with moderate water flow and nutrient-rich conditions, where they can establish and spread rapidly.', 'Mediterranean Mussel1.jpg', 'Mediterranean Mussel2.jpg');
